'Consulter utilisateur
     @startuml
          skinparam ParticipantPadding 20
          skinparam responseMessageBelowArrow true
          skinparam maxMessageSize 300
          '!theme spacelab
          hide footbox
          autonumber
     
          actor "Utilisateur:Administrateur" as user
          participant ":Interface" as interf
          participant ":Users" as system
          participant ":DB" as db
          title __"Utilisateur Administrateur"__: consulter un  utilisateur
          activate user
                  activate interf
                          activate system
                                  activate db
                                          user -> interf : demande la page de consultation d'un  utilisateur
                                          interf -> system : Envoie de la requête utilisateur
                                          system -> db : obtention des permissions de l'utilisateur
                                          db --> system : renvoie des permissions
                                          system -> system : vérification des permissions
                                          alt permissions insuffisantes
                                                  system --> interf: permission insuffisante
                                                  interf --> user: renvoie message "Vous ne disposez pas des permissions nécessaires pour effectuer cette action"
                                          else permissions suffisantes
                                                  system --> interf: permission suffisante
                                                  interf --> user : renvoie formulaire  pour consulter utilisateur
                                                  loop données non conformes ou utilisateur n'existe pas dans la BD
                                                          user -> interf:  soumettre formulaire
                                                          interf -> system:  validation des données
                                                          system -> system: validation du formulaire
                                                          alt données du formulaire conformes au modèle business utilisateur
                                                                  system->db: vérification de l'existence préalable du  utilisateur
                                                                  alt utilisateur existe
                                                                          db-->system: utilisateur existe


                                                                                  system-->interf: réussite: le utilisateur a été trouvé
                                                                                  interf -> user: renvoie message "Le utilisateur a été trouvé." + renvoie les détails du utilisateur

                                                                  else utilisateur n'existe pas
                                                                          db-->system: utilisateur n'existe pas
                                                                  deactivate db
                                                                  destroy db
                                                                  system-->interf: erreur: utilisateur n'existe pas
                                                                  interf -> user: renvoie message d'erreur "Ce utilisateur n'existe pas." + formulaire pour consulter utilisateur
                                                          end
                                                  else données non conformes
                                                          system-->interf: données du formulaire soumis sont invalides + détail des erreurs par champ
                                                  deactivate system
                                                  destroy system
                                                  interf --> user:  renvoie formulaire rempli pour éditer un  utilisateur + un message d'erreur par champ invalide
                                          deactivate user
                                          destroy user
                                  deactivate interf
                                  destroy interf
                          end
                  end
          end
          @enduml


'Créer utilisateur
@startuml
     skinparam ParticipantPadding 20
     skinparam responseMessageBelowArrow true
     skinparam maxMessageSize 300
     '!theme spacelab
     hide footbox
     autonumber

     actor "Utilisateur:Administrateur" as user
     participant ":Interface" as interf
     participant ":Users" as system
     participant ":DB" as db
     title __"Utilisateur Administrateur"__: créer un nouveau utilisateur
     activate user
             activate interf
                     activate system
                             activate db
                                     user -> interf : demande la page de création d'un nouveau utilisateur
                                     interf -> system : Envoie de la requête utilisateur
                                     system -> db : obtention des permissions de l'utilisateur
                                     db --> system : renvoie des permissions
                                     system -> system : vérification des permissions
                                     alt permissions insuffisantes
                                             system --> interf: permission insuffisante
                                             interf --> user: renvoie message "Vous ne disposez pas des permissions nécessaires pour effectuer cette action"
                                     else permissions suffisantes
                                             system --> interf: permission suffisante
                                             interf --> user : renvoie formulaire vide pour créer utilisateur
                                             loop données non conformes ou utilisateur existe déjà dans la BD
                                                     user -> interf:  soumettre formulaire rempli
                                                     interf -> system:  validation des données
                                                     system -> system: validation du formulaire
                                                     alt données du formulaire conformes au modèle business utilisateur
                                                             system->db: vérification de l'unicité du nouveau utilisateur
                                                             alt utilisateur est unique
                                                                     db-->system: utilisateur est unique
                                                                     system->db: débute la transaction
                                                                     system->db: exécute la modification
                                                                     system->db: commit la transaction
                                                                     alt transaction réussie
                                                                             db-->system: transaction réussie
                                                                             system-->interf: réussite: le utilisateur a été sauvegardé
                                                                             interf -> user: renvoie message "Le utilisateur a été sauvegardé." + renvoie formulaire vide pour créer utilisateur
                                                                     else transaction échouée
                                                                             db-->system: transaction refusée
                                                                             system->db: rollback la modification
                                                                             system-->interf: création du utilisateur échouée
                                                                             interf-->user: renvoie message d'erreur + formulaire rempli pour créer un nouveau utilisateur
                                                                     end
                                                             else utilisateur existe déjà
                                                                     db-->system: utilisateur existe déjà
                                                             deactivate db
                                                             destroy db
                                                             system-->interf: erreur: utilisateur existe déjà
                                                             interf -> user: renvoie message d'erreur "Ce utilisateur existe déjà." + formulaire rempli pour créer un nouveau utilisateur
                                                     end
                                             else données non conformes
                                                     system-->interf: données du formulaire soumis sont invalides + détail des erreurs par champ
                                             deactivate system
                                             destroy system
                                             interf --> user:  renvoie formulaire rempli pour créer un nouveau utilisateur + un message d'erreur par champ invalide
                                     deactivate user
                                     destroy user
                             deactivate interf
                             destroy interf
                     end
             end
     end
     @enduml
     
     'Éditer utilisateur
     @startuml
          skinparam ParticipantPadding 20
          skinparam responseMessageBelowArrow true
          skinparam maxMessageSize 300
          '!theme spacelab
          hide footbox
          autonumber
     
          actor "Utilisateur:Administrateur" as user
          participant ":Interface" as interf
          participant ":Users" as system
          participant ":DB" as db
          title __"Utilisateur Administrateur"__: éditer un  utilisateur
          activate user
                  activate interf
                          activate system
                                  activate db
                                          user -> interf : demande la page d'édition d'un  utilisateur
                                          interf -> system : Envoie de la requête utilisateur
                                          system -> db : obtention des permissions de l'utilisateur
                                          db --> system : renvoie des permissions
                                          system -> system : vérification des permissions
                                          alt permissions insuffisantes
                                                  system --> interf: permission insuffisante
                                                  interf --> user: renvoie message "Vous ne disposez pas des permissions nécessaires pour effectuer cette action"
                                          else permissions suffisantes
                                                  system --> interf: permission suffisante
                                                  interf --> user : renvoie formulaire  pour éditer utilisateur
                                                  loop données non conformes ou utilisateur n'existe pas dans la BD
                                                          user -> interf:  soumettre formulaire rempli
                                                          interf -> system:  validation des données
                                                          system -> system: validation du formulaire
                                                          alt données du formulaire conformes au modèle business utilisateur
                                                                  system->db: vérification de l'existence préalable du  utilisateur
                                                                  alt utilisateur existe
                                                                          db-->system: utilisateur existe
                                                                          system->db: débute la transaction
                                                                          system->db: exécute la modification
                                                                          system->db: commit la transaction
                                                                          alt transaction réussie
                                                                                  db-->system: transaction réussie
                                                                                  system-->interf: réussite: le utilisateur a été sauvegardé
                                                                                  interf -> user: renvoie message "Le utilisateur a été sauvegardé." + renvoie formulaire  pour éditer utilisateur
                                                                          else transaction échouée
                                                                                  db-->system: transaction refusée
                                                                                  system->db: rollback la modification
                                                                                  system-->interf: édition du utilisateur échouée
                                                                                  interf-->user: renvoie message d'erreur + formulaire rempli pour éditer un  utilisateur
                                                                          end
                                                                  else utilisateur n'existe pas
                                                                          db-->system: utilisateur n'existe pas
                                                                  deactivate db
                                                                  destroy db
                                                                  system-->interf: erreur: utilisateur n'existe pas
                                                                  interf -> user: renvoie message d'erreur "Ce utilisateur n'existe pas." + formulaire rempli pour éditer un  utilisateur
                                                          end
                                                  else données non conformes
                                                          system-->interf: données du formulaire soumis sont invalides + détail des erreurs par champ
                                                  deactivate system
                                                  destroy system
                                                  interf --> user:  renvoie formulaire rempli pour éditer un  utilisateur + un message d'erreur par champ invalide
                                          deactivate user
                                          destroy user
                                  deactivate interf
                                  destroy interf
                          end
                  end
          end
          @enduml


          'Supprimer utilisateur
               @startuml
                    skinparam ParticipantPadding 20
                    skinparam responseMessageBelowArrow true
                    skinparam maxMessageSize 300
                    '!theme spacelab
                    hide footbox
                    autonumber

                    actor "Utilisateur:Administrateur" as user
                    participant ":Interface" as interf
                    participant ":Users" as system
                    participant ":DB" as db
                    title __"Utilisateur Administrateur"__: supprimer un  utilisateur
                    activate user
                            activate interf
                                    activate system
                                            activate db
                                                    user -> interf : demande la page de suppression d'un  utilisateur
                                                    interf -> system : Envoie de la requête utilisateur
                                                    system -> db : obtention des permissions de l'utilisateur
                                                    db --> system : renvoie des permissions
                                                    system -> system : vérification des permissions
                                                    alt permissions insuffisantes
                                                            system --> interf: permission insuffisante
                                                            interf --> user: renvoie message "Vous ne disposez pas des permissions nécessaires pour effectuer cette action"
                                                    else permissions suffisantes
                                                            system --> interf: permission suffisante
                                                            interf --> user : renvoie formulaire  pour supprimer utilisateur
                                                            loop données non conformes ou utilisateur n'existe pas dans la BD
                                                                    user -> interf:  soumettre formulaire rempli
                                                                    interf -> system:  validation des données
                                                                    system -> system: validation du formulaire
                                                                    alt données du formulaire conformes au modèle business utilisateur
                                                                            system->db: vérification de l'existence préalable du  utilisateur
                                                                            alt utilisateur existe
                                                                                    db-->system: utilisateur existe
                                                                                    system->db: débute la transaction
                                                                                    system->db: exécute la modification
                                                                                    system->db: commit la transaction
                                                                                    alt transaction réussie
                                                                                            db-->system: transaction réussie
                                                                                            system-->interf: réussite: le utilisateur a été supprimé
                                                                                            interf -> user: renvoie message "Le utilisateur a été supprimé." + renvoie formulaire  pour supprimer utilisateur
                                                                                    else transaction échouée
                                                                                            db-->system: transaction refusée
                                                                                            system->db: rollback la modification
                                                                                            system-->interf: suppression du utilisateur échouée
                                                                                            interf-->user: renvoie message d'erreur + formulaire rempli pour supprimer un  utilisateur
                                                                                    end
                                                                            else utilisateur n'existe pas
                                                                                    db-->system: utilisateur n'existe pas
                                                                            deactivate db
                                                                            destroy db
                                                                            system-->interf: erreur: utilisateur n'existe pas
                                                                            interf -> user: renvoie message d'erreur "Ce utilisateur n'existe pas." + formulaire rempli pour supprimer un  utilisateur
                                                                    end
                                                            else données non conformes
                                                                    system-->interf: données du formulaire soumis sont invalides + détail des erreurs par champ
                                                            deactivate system
                                                            destroy system
                                                            interf --> user:  renvoie formulaire rempli pour supprimer un  utilisateur + un message d'erreur par champ invalide
                                                    deactivate user
                                                    destroy user
                                            deactivate interf
                                            destroy interf
                                    end
                            end
                    end
                    @enduml
